services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: conregivr03test.azurecr.io/api:latest
    ports:
      - "8000:8000"
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 1
